apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nb-deploy
  labels:
    app: nb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nb
  template:
    metadata:
      labels:
        app: nb
    spec:
      containers:
        - name: nb
          image: birdstar/all-spark-notebook-kg:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: KG_URL
            value: "http://kg-svc.ibmdsxuser-buildin:9999"
          ports:
            - containerPort: 9898


